module.exports = {
    name: '.',
    aliases: [],
    description: ".",
    async execute(client, message, args, command, Discord) {

        const messages = [
            "https://imgur.com/F27ErtB",
            "https://imgur.com/lJpmFYF",
            "https://imgur.com/Jfdb0hR",
            "https://imgur.com/KotwBpK",
            "https://imgur.com/8C36cns",
            "https://imgur.com/ap583vi",
            "https://imgur.com/Fz6zQBi",
            "https://imgur.com/eiTztN7",
            "https://imgur.com/9ZRXdQ5",
            "https://imgur.com/yrOhBdZ",
            "https://imgur.com/kJimVPh",
            "https://imgur.com/dWo9O73",
            "https://imgur.com/wVspuon",
            "https://imgur.com/qlYbxK6",
            "https://imgur.com/yjxanxk",
            "https://imgur.com/nfKP3wh",
            "https://imgur.com/SxJeaZ1",
            "https://imgur.com/idxYOlH",
            "https://imgur.com/1rceRGp",
            "https://imgur.com/uHjryY9",
            "https://imgur.com/FwvfALt",
            "https://imgur.com/qSHJ6dJ",
            "https://imgur.com/zuFRFar",
            "https://imgur.com/KL1p7T5",
            "https://imgur.com/ELsgrM6",
            "https://imgur.com/FzRJTBH",
            "https://imgur.com/597ah1n",
            "https://imgur.com/sBTV4gw",
            "https://imgur.com/TcIyrXM",
            "https://imgur.com/v9z09Ue",
            "https://imgur.com/XfZXDpG",
            "https://imgur.com/wfEzhl6",
            "https://imgur.com/Q8wHlko",
            "https://imgur.com/4AVGqZo",
            "https://imgur.com/ksNKXdq",
            "https://imgur.com/HrXzdSg",
            "https://imgur.com/GtpA1WX",
            "https://imgur.com/EVzMdKg",
            "https://imgur.com/6LVIACI",
            "https://imgur.com/BLucSwg",
            "https://imgur.com/IqJjrFC",
            "https://imgur.com/tfPr008",
            "https://imgur.com/hM4N264",
            "https://imgur.com/k4N6kTL",
            "https://imgur.com/aS7CX4o",
            "https://imgur.com/GfBQkfS",
            "https://imgur.com/xzTHMBi",
            "https://imgur.com/m3ohWcX",
            "https://imgur.com/DoJnjUu",
            "https://imgur.com/aD9Ftfk",
            "https://imgur.com/eSJ8F8H",
            "https://imgur.com/jtdoAHD",
            "https://imgur.com/SCmwEpg",
            "https://imgur.com/U3ZxiDm",
            "https://imgur.com/HxHjmvM",
            "https://imgur.com/dX7xzDq",
            "https://imgur.com/j6OGv2k",
            "https://imgur.com/CvPX6Mm",
            "https://imgur.com/LfjCbH7",
            "https://imgur.com/uHx24El",
            "https://imgur.com/N3sTeoQ",
            "https://imgur.com/N8sAXVY",
            "https://imgur.com/H1z9EJm",
            "https://imgur.com/HQU16O3",
            "https://imgur.com/bF6Xx6N",
            "https://imgur.com/lC0vZdB",
            "https://imgur.com/PsfIYFt",
            "https://imgur.com/tirYrnc",
            "https://imgur.com/5ure6mv",
            "https://imgur.com/G7LjGHS",
            "https://imgur.com/3OvqNAh",
            "https://imgur.com/5cGdIn9",
            "https://imgur.com/CYKtxvj",
            "https://imgur.com/TiDRbYi",
            "https://imgur.com/toTzpWH",
            "https://imgur.com/DLna5TI",
            "https://imgur.com/gqAI9pi",
            "https://imgur.com/0jyOJ0x",
            "https://imgur.com/dCIxDzs",
            "https://imgur.com/Ih8LKgY",
            "https://imgur.com/TUWdAnZ",
            "https://imgur.com/ugdabBl",
            "https://imgur.com/n4P8kCI",
            "https://imgur.com/v6sZbIV",
            "https://imgur.com/U1B0694"
        ];

        const pfp = messages[Math.floor(Math.random() * messages.length)];

        return message.channel.send([
            `**Here's a PFP** (non-animated)`,
            `${pfp}`
        ]);
    }
}